name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        ruff check app/ tests/
    
    - name: Format check with black
      run: |
        black --check app/ tests/
    
    - name: Run unit tests only (no real services)
      run: |
        # Only run mocked tests - safe for public CI
        pytest tests/unit/ -v --cov=app --cov-report=xml
      env:
        # Dummy environment variables for CI
        SUPABASE_URL: "https://dummy.supabase.co"
        SUPABASE_SERVICE_ROLE_KEY: "dummy_key"
        SUPABASE_DB_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
        SUPABASE_JWT_SECRET: "dummy_secret"
        UPSTASH_REDIS_REST_URL: "https://dummy.upstash.io"
        UPSTASH_REDIS_REST_TOKEN: "dummy_token"
        VAPI_PRIVATE_KEY: "dummy_vapi_key"

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image (test build only)
      run: |
        docker build -t voice-gmail-assistant:test .
    
    - name: Verify Docker image structure
      run: |
        # Just verify the image was built correctly
        docker images | grep voice-gmail-assistant